name: Healthcheck pipeline

on:
  schedule:
    - cron:  '*/5 * * * *'
    
jobs:
  healthcheck-pipeline:
    runs-on: ubuntu-18.04
    steps:
      - name: Check the deployed service URL
        uses: jtalk/url-health-check-action@v1.2
        with:
          url: https://full-stack-seeve-pokedex.herokuapp.com/